#!/usr/bin/env bash
#
# CONDUCTOR universal hook template
# hook_id: pretool-large-file-read-guard
# trigger: pretool
# action: Block Read of files >= ${CONDUCTOR_LARGE_FILE_LINE_THRESHOLD}
#         lines unless offset/limit is supplied (or override env set).
# compile_targets: claude
# fallback: rule-text-reminder
#
# Generated by adapters/<tool>/transform.sh.
#
# Enforces:
#   - meta-discipline.md token-economy section: range reads mandatory for
#     files exceeding the line threshold.
#
# Behavior:
#   1. Parse PreToolUse stdin payload.
#   2. If tool_name != Read → allow (silent exit 0).
#   3. Resolve file_path; if missing or unreadable → allow (let Read tool error).
#   4. wc -l file. If lines < threshold → allow.
#   5. If offset OR limit present → allow.
#   6. If override env set → allow.
#   7. Else → deny with diagnostic message recommending offset/limit or Grep.
#
# Override (rare, e.g. small JSON config that happens to be wide):
#   ${CONDUCTOR_LARGE_READ_OVERRIDE_ENV}=1
#
# Exit code meaning in PreToolUse hooks (Claude Code):
#   0 with no JSON output                 → allow
#   0 with {"permissionDecision":"deny"}  → block with reason (shown to LLM)
#   non-zero                              → allow (fail-open)

set -u

# Placeholders filled by adapters/<tool>/transform.sh:
#   ${CONDUCTOR_LARGE_FILE_LINE_THRESHOLD}  — line threshold (default 500)
#   ${CONDUCTOR_LARGE_READ_OVERRIDE_ENV}    — env var to bypass (default CONDUCTOR_ALLOW_LARGE_READ)

THRESHOLD="${CONDUCTOR_LARGE_FILE_LINE_THRESHOLD:-500}"
OVERRIDE_ENV_NAME="${CONDUCTOR_LARGE_READ_OVERRIDE_ENV:-CONDUCTOR_ALLOW_LARGE_READ}"

# Honor opt-out before any work.
OVERRIDE_VAL="$(/usr/bin/printenv "$OVERRIDE_ENV_NAME" 2>/dev/null || true)"
[ "$OVERRIDE_VAL" = "1" ] && exit 0

command -v python3 >/dev/null 2>&1 || exit 0

PAYLOAD_RAW="$(/bin/cat 2>/dev/null || true)"
[ -n "$PAYLOAD_RAW" ] || exit 0

# Single python pass extracts tool_name + file_path + offset/limit presence.
# Output format: TOOL=<name>\nPATH=<file>\nHAS_OFFSET=<0|1>\nHAS_LIMIT=<0|1>
PARSED=$(PAYLOAD_RAW="$PAYLOAD_RAW" python3 -c "
import json, os, sys
try:
    d = json.loads(os.environ.get('PAYLOAD_RAW', '{}'))
except Exception:
    sys.exit(0)
if d.get('tool_name', '') != 'Read':
    sys.exit(0)
inp = d.get('tool_input', {}) or {}
fp = inp.get('file_path', '') or ''
has_off = '1' if (inp.get('offset') is not None) else '0'
has_lim = '1' if (inp.get('limit') is not None) else '0'
print('TOOL=Read')
print('PATH=' + fp)
print('HAS_OFFSET=' + has_off)
print('HAS_LIMIT=' + has_lim)
" 2>/dev/null)

[ -n "$PARSED" ] || exit 0

FILE_PATH=""
HAS_OFFSET="0"
HAS_LIMIT="0"
while IFS='=' read -r key val; do
  case "$key" in
    PATH) FILE_PATH="$val" ;;
    HAS_OFFSET) HAS_OFFSET="$val" ;;
    HAS_LIMIT) HAS_LIMIT="$val" ;;
  esac
done <<EOF
$PARSED
EOF

# Allow if range read.
if [ "$HAS_OFFSET" = "1" ] || [ "$HAS_LIMIT" = "1" ]; then
  exit 0
fi

# File must exist + be readable for size check; else let Read tool handle errors.
[ -n "$FILE_PATH" ] || exit 0
[ -r "$FILE_PATH" ] || exit 0
[ -f "$FILE_PATH" ] || exit 0

LINES=$(/usr/bin/wc -l < "$FILE_PATH" 2>/dev/null | /usr/bin/tr -d ' ')
case "$LINES" in
  ''|*[!0-9]*) exit 0 ;;
esac

[ "$LINES" -lt "$THRESHOLD" ] && exit 0

# Build deny payload.
REASON="[large-file-read-guard] File '${FILE_PATH}' has ${LINES} lines (threshold ${THRESHOLD}). Pass offset/limit (e.g. limit:100, offset:0) to range-read, or use Grep to find the specific symbol/section first. Override (rare, e.g. wide JSON config): set ${OVERRIDE_ENV_NAME}=1 in environment."

REASON="$REASON" python3 -c "
import json, os
print(json.dumps({
    'hookSpecificOutput': {
        'hookEventName': 'PreToolUse',
        'permissionDecision': 'deny',
        'permissionDecisionReason': os.environ.get('REASON', ''),
    }
}))
"
exit 0
