#!/usr/bin/env bash
#
# CONDUCTOR universal hook template
# hook_id: stop-cache-hit-baseline-check
# trigger: stop
# action: Read latest Claude Code session JSONL, compute cache hit rate, emit
#         a non-blocking diagnostic reminder when below baseline.
# compile_targets: claude
# fallback: rule-text-reminder
#
# Generated by adapters/<tool>/transform.sh.
#
# Enforces:
#   - meta-discipline.md token-economy section (cache hit baseline)
#
# Behavior:
#   1. Locate latest session JSONL under ~/.claude/projects/<encoded>/*.jsonl.
#   2. Sum cache_read_input_tokens vs uncached input_tokens via python3.
#   3. If hit_rate < ${CONDUCTOR_CACHE_HIT_FLOOR_PERCENT}% AND total
#      effective input tokens >= ${CONDUCTOR_CACHE_TOTAL_FLOOR}, emit a
#      stderr reminder listing the 5 candidate anti-patterns.
#   4. exit 0 (non-blocking).
#
# Override (silence reminder, e.g. CI sessions):
#   ${CONDUCTOR_CACHE_SKIP_ENV}=1
#
# Skip conditions:
#   - python3 missing
#   - no session JSONL found
#   - session token volume below floor (too short to draw conclusions)
#   - skip env var set

set -u

# Placeholders filled by adapters/<tool>/transform.sh:
#   ${CONDUCTOR_CACHE_HIT_FLOOR_PERCENT}  — target floor (default 80)
#   ${CONDUCTOR_CACHE_TOTAL_FLOOR}        — minimum total tokens before report (default 5000)
#   ${CONDUCTOR_CACHE_SKIP_ENV}           — env var to silence (default CONDUCTOR_SKIP_CACHE_CHECK)
#   ${CONDUCTOR_ANTI_PATTERNS_PATH}       — relative path to anti-patterns doc

FLOOR_PCT="${CONDUCTOR_CACHE_HIT_FLOOR_PERCENT:-80}"
TOTAL_FLOOR="${CONDUCTOR_CACHE_TOTAL_FLOOR:-5000}"
SKIP_ENV_NAME="${CONDUCTOR_CACHE_SKIP_ENV:-CONDUCTOR_SKIP_CACHE_CHECK}"
ANTI_PATTERNS_DOC="${CONDUCTOR_ANTI_PATTERNS_PATH:-core/anti-patterns/README.md}"

# Honor user opt-out without inspecting payload.
SKIP_VAL="$(/usr/bin/printenv "$SKIP_ENV_NAME" 2>/dev/null || true)"
[ "$SKIP_VAL" = "1" ] && exit 0

command -v python3 >/dev/null 2>&1 || exit 0

# Allow tests to inject a fixture directly.
FIXTURE="${CONDUCTOR_CACHE_TEST_FIXTURE:-}"
SESSION_PATH=""

if [ -n "$FIXTURE" ]; then
  [ -f "$FIXTURE" ] || exit 0
  SESSION_PATH="$FIXTURE"
else
  # Find newest *.jsonl under ~/.claude/projects/.
  if [ ! -d "$HOME/.claude/projects" ]; then
    exit 0
  fi
  SESSION_PATH=$(/usr/bin/find "$HOME/.claude/projects" -name '*.jsonl' -type f 2>/dev/null \
    | while IFS= read -r f; do
        m=$(/usr/bin/stat -f '%m' "$f" 2>/dev/null || /usr/bin/stat -c '%Y' "$f" 2>/dev/null || echo 0)
        printf '%s\t%s\n' "$m" "$f"
      done \
    | /usr/bin/sort -rn \
    | /usr/bin/head -n 1 \
    | /usr/bin/cut -f2-)
  [ -n "$SESSION_PATH" ] && [ -f "$SESSION_PATH" ] || exit 0
fi

# Parse + decide. python3 prints a single line: "<hit_rate> <total_eff>".
RESULT=$(SESSION="$SESSION_PATH" python3 - <<'PYEOF' 2>/dev/null
import json, os, sys
path = os.environ.get("SESSION", "")
total_input = 0
total_cache_read = 0
try:
    with open(path, "r", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except Exception:
                continue
            usage = (obj.get("message") or {}).get("usage") or {}
            total_input += usage.get("input_tokens") or 0
            total_cache_read += usage.get("cache_read_input_tokens") or 0
except Exception:
    sys.exit(0)
total_eff = total_input + total_cache_read
hit = (total_cache_read / total_eff * 100.0) if total_eff > 0 else 100.0
print(f"{hit:.1f} {total_eff}")
PYEOF
)

[ -n "$RESULT" ] || exit 0

HIT_RATE="${RESULT% *}"
TOTAL_EFF="${RESULT##* }"

# Floor check (integer compare on TOTAL_EFF).
case "$TOTAL_EFF" in
  ''|*[!0-9]*) exit 0 ;;
esac
[ "$TOTAL_EFF" -lt "$TOTAL_FLOOR" ] && exit 0

# Compare HIT_RATE (float) to FLOOR_PCT (int) using awk.
BELOW=$(/usr/bin/awk -v h="$HIT_RATE" -v f="$FLOOR_PCT" 'BEGIN { print (h+0 < f+0) ? "1" : "0" }')
[ "$BELOW" = "1" ] || exit 0

# Emit non-blocking reminder to stderr (Stop hook stderr is surfaced to user).
/bin/cat >&2 <<EOF

[stop-hook cache-baseline] Session cache hit rate: ${HIT_RATE}% (floor ${FLOOR_PCT}%, eff input ${TOTAL_EFF} tokens).

Likely causes (top 5 anti-patterns):
  1. Dynamic prompt prefix — values change every turn, breaking cache key.
  2. Large-file Read without offset/limit — pulls entire file into context.
  3. Monolithic rule file edited mid-session — invalidates cached system prompt.
  4. No sub-agent isolation — long-running task accumulates context in main thread.
  5. Frequent CLAUDE.md / settings edits during session — busts the prefix cache.

Diagnostic guide: ${ANTI_PATTERNS_DOC}
Silence (intentional): export ${SKIP_ENV_NAME}=1

EOF
exit 0
