#!/usr/bin/env bash
#
# CONDUCTOR universal hook template
# hook_id: pretool-commit-test-coverage-check
# trigger: pretool
# action: Soft-warn at commit time when a new feature-shaped source file is added
#         with no accompanying test file in the same commit.
# compile_targets: claude
# fallback: rule-text-reminder
#
# Generated by adapters/<tool>/transform.sh.
#
# Script form of quality-gates Q3. Soft warn, never blocks.
#
# Enforces:
#   - quality-gates.md Q3 (test coverage sync) — a new feature/route/page/endpoint/
#     service should land with its test in the same commit.
#
# Behavior:
#   1. Parse PreToolUse stdin payload (same method as pretool-agent-routing).
#   2. If tool_name != Bash → allow. If command is not `git commit` → allow.
#   3. From `git diff --cached --name-only --diff-filter=A`, collect newly-ADDED
#      source files matching ts|tsx.
#   4. Heuristic (kept generic on purpose): treat an added source file as
#      "feature-shaped" if its path contains one of: route, page, endpoint,
#      service, api, handler, controller, feature  (case-insensitive). Pure type
#      files / barrels / configs rarely contain those tokens, so they don't trip it.
#   5. If a feature-shaped added file exists AND no NEW test file is staged
#      (path containing test, spec, __tests__, or e2e) → emit a soft confirmation
#      (permissionDecision: ask + permissionDecisionReason) citing Q3.
#   6. Override env / any error → allow (silent exit 0).
#
# Override (skip this check for a commit):
#   CONDUCTOR_SKIP_TEST_COVERAGE_HOOK=1
#
# Exit code meaning in PreToolUse hooks (Claude Code):
#   0 with no JSON output                                    → allow (silent)
#   0 with {"permissionDecision":"ask","permissionDecisionReason":...}
#       → surface the reason and route to the permission flow; the orchestrator
#         approves and proceeds (or justifies). Does NOT block and does NOT
#         auto-approve. This is the documented non-blocking soft-warn and matches
#         pretool-agent-routing.sh.template's deny+reason shape (here: ask+reason).
#   non-zero                                                 → allow (fail-open)

set -u

# Placeholders filled by adapters/<tool>/transform.sh:
#   ts|tsx  — alternation of source extensions (default ts|tsx)

# Honor opt-out before any work.
[ "${CONDUCTOR_SKIP_TEST_COVERAGE_HOOK:-}" = "1" ] && exit 0

SRC_GLOB="${CONDUCTOR_SOURCE_GLOB:-ts|tsx}"

command -v /usr/bin/python3 >/dev/null 2>&1 || exit 0

export PAYLOAD_RAW="$(/bin/cat 2>/dev/null || true)"
[ -n "${PAYLOAD_RAW:-}" ] || exit 0

CMD=$(/usr/bin/python3 -c "
import json, os, sys
try:
    d = json.loads(os.environ.get('PAYLOAD_RAW', '{}'))
    if d.get('tool_name', '') != 'Bash':
        sys.exit(0)
    inp = d.get('tool_input', {}) or {}
    sys.stdout.write(inp.get('command', '') or '')
except Exception:
    sys.exit(0)
" 2>/dev/null)

case "$CMD" in
  *"git commit"*) : ;;
  *) exit 0 ;;
esac

# Newly-added source files in this commit (added files only).
ADDED_SRC=$(git diff --cached --name-only --diff-filter=A 2>/dev/null | /usr/bin/grep -E "\.(${SRC_GLOB})$" || true)
[ -n "$ADDED_SRC" ] || exit 0

# Feature-shaped heuristic: path segment hints at a feature/route/page/endpoint/service.
# Kept deliberately generic so it works across stacks; excludes test files themselves.
# The substring match is intentionally loose (e.g. `pageant.ts` can trip `page`) — acceptable
# because this is a soft `ask` warn the orchestrator can wave through, not a hard block.
FEATURE_RE='(route|page|endpoint|service|api|handler|controller|feature)'
TEST_RE='(test|spec|__tests__|e2e)'

FEATURE_NEW=$(printf '%s\n' "$ADDED_SRC" \
  | /usr/bin/grep -ivE "$TEST_RE" \
  | /usr/bin/grep -icE "$FEATURE_RE" || true)
case "$FEATURE_NEW" in
  ''|*[!0-9]*) exit 0 ;;
esac
[ "$FEATURE_NEW" -ge 1 ] || exit 0

# Any NEW test file staged in this commit (added; covers the common case of a new feature).
NEW_TESTS=$(git diff --cached --name-only --diff-filter=A 2>/dev/null | /usr/bin/grep -icE "$TEST_RE" || true)
case "$NEW_TESTS" in
  ''|*[!0-9]*) NEW_TESTS=0 ;;
esac

[ "$NEW_TESTS" -ge 1 ] && exit 0

REASON="[test-coverage-check] A new feature-shaped source file is staged but no new test file (path with test/spec/__tests__/e2e) is in this commit. Per quality-gates.md Q3, add or update the covering test in the same commit. (Skip once: set CONDUCTOR_SKIP_TEST_COVERAGE_HOOK=1.)"

REASON="$REASON" /usr/bin/python3 -c "
import json, os
print(json.dumps({
    'hookSpecificOutput': {
        'hookEventName': 'PreToolUse',
        'permissionDecision': 'ask',
        'permissionDecisionReason': os.environ.get('REASON', ''),
    }
}))
"
exit 0
