#!/usr/bin/env bash
#
# CONDUCTOR universal hook template
# hook_id: pretool-commit-current-work-check
# trigger: pretool
# action: Soft-warn at commit time when 3+ source files are staged but
#         docs/CURRENT_WORK.md is not part of the same commit.
# compile_targets: claude
# fallback: rule-text-reminder
#
# Generated by adapters/<tool>/transform.sh.
#
# Commit-time companion to stop-session-log-check.sh.template. Soft warn, never blocks.
#
# Enforces:
#   - operations.md O2 (CURRENT_WORK.md must update when work happens) — caught at
#     commit time instead of (only) at session stop.
#
# Behavior:
#   1. Parse PreToolUse stdin payload (same method as pretool-agent-routing).
#   2. If tool_name != Bash → allow (silent exit 0).
#   3. If the command is not a `git commit` → allow (silent exit 0).
#   4. Count staged source files matching ts|tsx.
#   5. If 3+ staged source files AND docs/CURRENT_WORK.md is NOT staged
#      → emit a soft confirmation (permissionDecision: ask + permissionDecisionReason).
#   6. Override env / any error → allow (silent exit 0).
#
# Override (skip this check for a commit):
#   CONDUCTOR_SKIP_CURRENT_WORK_HOOK=1
#
# Exit code meaning in PreToolUse hooks (Claude Code):
#   0 with no JSON output                                    → allow (silent)
#   0 with {"permissionDecision":"ask","permissionDecisionReason":...}
#       → surface the reason and route to the permission flow; the orchestrator
#         approves and proceeds (or justifies). Does NOT block and does NOT
#         auto-approve. This is the documented non-blocking soft-warn and matches
#         pretool-agent-routing.sh.template's deny+reason shape (here: ask+reason).
#   0 with {"permissionDecision":"deny"}                     → block with reason
#   non-zero                                                 → allow (fail-open)

set -u

# Placeholders filled by adapters/<tool>/transform.sh:
#   ts|tsx        — alternation of source extensions (default ts|tsx)
#   docs/CURRENT_WORK.md  — session-log path (default docs/CURRENT_WORK.md)

# Honor opt-out before any work.
[ "${CONDUCTOR_SKIP_CURRENT_WORK_HOOK:-}" = "1" ] && exit 0

SRC_GLOB="${CONDUCTOR_SOURCE_GLOB:-ts|tsx}"
CURRENT_WORK="${CONDUCTOR_CURRENT_WORK_PATH:-docs/CURRENT_WORK.md}"

command -v /usr/bin/python3 >/dev/null 2>&1 || exit 0

# Read payload from stdin into env var so python can parse it safely.
export PAYLOAD_RAW="$(/bin/cat 2>/dev/null || true)"
[ -n "${PAYLOAD_RAW:-}" ] || exit 0

# Extract the Bash command (same extraction shape the existing hooks use).
CMD=$(/usr/bin/python3 -c "
import json, os, sys
try:
    d = json.loads(os.environ.get('PAYLOAD_RAW', '{}'))
    if d.get('tool_name', '') != 'Bash':
        sys.exit(0)
    inp = d.get('tool_input', {}) or {}
    sys.stdout.write(inp.get('command', '') or '')
except Exception:
    sys.exit(0)
" 2>/dev/null)

# Only act on git commit commands.
case "$CMD" in
  *"git commit"*) : ;;
  *) exit 0 ;;
esac

# Count staged source files (additions, modifications, etc.).
STAGED_SRC=$(git diff --cached --name-only 2>/dev/null | /usr/bin/grep -cE "\.(${SRC_GLOB})$" || true)
case "$STAGED_SRC" in
  ''|*[!0-9]*) exit 0 ;;
esac

[ "$STAGED_SRC" -ge 3 ] || exit 0

# Is the session log itself part of this commit?
if git diff --cached --name-only 2>/dev/null | /usr/bin/grep -qF "$CURRENT_WORK"; then
  exit 0
fi

REASON="[current-work-check] ${STAGED_SRC} source file(s) are staged but ${CURRENT_WORK} is not in this commit. Per operations.md O2, append the planned change to ${CURRENT_WORK} before committing so the session log stays in sync. (Skip once: set CONDUCTOR_SKIP_CURRENT_WORK_HOOK=1.)"

REASON="$REASON" /usr/bin/python3 -c "
import json, os
print(json.dumps({
    'hookSpecificOutput': {
        'hookEventName': 'PreToolUse',
        'permissionDecision': 'ask',
        'permissionDecisionReason': os.environ.get('REASON', ''),
    }
}))
"
exit 0
