#!/usr/bin/env bash
#
# CONDUCTOR universal hook template
# hook_id: stop-r6-review-check
# trigger: stop
# action: Remind to run pre-merge code review (Q2) when feature/fix/chore branch
#         has a recently-pushed open PR.
# compile_targets: claude
# fallback: rule-text-reminder
#
# Generated by adapters/<tool>/transform.sh.
#
# Enforces:
#   - quality-gates.md Q2 (pre-merge code review on open PR)
#
# Skip conditions:
#   - current branch is in CONDUCTOR_DIRECT_PUSH_BRANCHES (no PR expected)
#   - no open PR for current branch
#   - no push in last STALE_MINUTES (nothing new to review)
#   - cool-down flag present (review reminder already shown recently)

set -u

# Placeholders filled by adapters/<tool>/transform.sh:
#   develop|main|release|HEAD  — pipe-separated branch list (default: develop|main|release|HEAD)
#   30         — recent-push window (default 30)
#   1800      — cool-down per PR (default 1800 = 30 min)
#   /code-review        — slash command or script to run review (default /code-review)

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT" || exit 0

command -v git >/dev/null 2>&1 || exit 0
command -v gh  >/dev/null 2>&1 || exit 0

DIRECT_PUSH="${CONDUCTOR_DIRECT_PUSH_BRANCHES:-develop|main|release|HEAD}"
STALE_MINUTES="${CONDUCTOR_STALE_MINUTES:-30}"
COOLDOWN="${CONDUCTOR_COOLDOWN_SECONDS:-1800}"
REVIEW_COMMAND="${CONDUCTOR_REVIEW_COMMAND:-/code-review}"

BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
[ -n "$BRANCH" ] || exit 0

# Skip direct-push branches.
if echo "$BRANCH" | /usr/bin/grep -qE "^(${DIRECT_PUSH})$"; then
  exit 0
fi

# Recent-push detection.
THIRTY_MIN_AGO=$(date -v-"${STALE_MINUTES}"M '+%s' 2>/dev/null || date -d "${STALE_MINUTES} minutes ago" '+%s' 2>/dev/null)
[ -n "$THIRTY_MIN_AGO" ] || exit 0

RECENT_PUSH=$(git reflog --date=unix 2>/dev/null \
  | /usr/bin/awk -v t="$THIRTY_MIN_AGO" '
      /push/ {
        if (match($0, /\{([0-9]+)\}/, m)) {
          if (m[1]+0 >= t+0) { print; exit }
        }
      }')
[ -n "$RECENT_PUSH" ] || exit 0

# Open PR for current branch.
PR_JSON=$(gh pr list --head "$BRANCH" --state open --json url,number --limit 1 2>/dev/null)
[ -n "$PR_JSON" ] && [ "$PR_JSON" != "[]" ] || exit 0

PR_URL=$(printf '%s' "$PR_JSON" | /usr/bin/sed -n 's/.*"url":"\([^"]*\)".*/\1/p')
PR_NUM=$(printf '%s' "$PR_JSON" | /usr/bin/sed -n 's/.*"number":\([0-9]*\).*/\1/p')
[ -n "$PR_NUM" ] || exit 0

# Cool-down per PR.
FLAG="/tmp/conductor-q2-flag-${USER:-unknown}-${PR_NUM}"
if [ -f "$FLAG" ]; then
  FLAG_AGE=$(( $(date +%s) - $(/usr/bin/stat -f %m "$FLAG" 2>/dev/null || /usr/bin/stat -c %Y "$FLAG" 2>/dev/null || echo 0) ))
  [ "$FLAG_AGE" -lt "$COOLDOWN" ] && exit 0
fi
touch "$FLAG"

/bin/cat <<EOF
{"decision":"block","reason":"[stop-hook Q2] Open PR #${PR_NUM} on branch \`${BRANCH}\` with recent push. Run \`${REVIEW_COMMAND} ${PR_URL}\` before merge per universal-rules/quality-gates.md Q2 (pre-merge code review). Docs-only PRs are exempt."}
EOF
